### ISSUE TITLE
Having issues uploading

### ISSUE THREAD

**Issue by Bradw-17** [fabriziofiorucci/Streamdeck#1]
I keep getting this error: 

streamdeck:554:1: error: 'KeyboardKeycode' does not name a type; did you mean 'Keyboard'?
 KeyboardKeycode keyPressed=KEY_RESERVED;
 ^~~~~~~~~~~~~~~
 Keyboard
streamdeck:555:1: error: 'ConsumerKeycode' does not name a type
 ConsumerKeycode consumerKeyPressed=0;
 ^~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:556:21: warning: invalid conversion from 'const char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
 uint8_t *bitmapName="";
                     ^~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino: In function 'void setup()':
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:597:14: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
   bitmapName=bitmap_boot;
              ^~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino: In function 'void loop()':
streamdeck:613:9: error: 'keyPressed' was not declared in this scope
         keyPressed=KEY_F20;
         ^~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:614:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_micmute;
                    ^~~~~~~~~~~~~~
streamdeck:618:20: error: 'KEY_VOLUME_MUTE' was not declared in this scope
         keyPressed=KEY_VOLUME_MUTE;
                    ^~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:618:20: note: suggested alternative: 'KEY_DELETE'
         keyPressed=KEY_VOLUME_MUTE;
                    ^~~~~~~~~~~~~~~
                    KEY_DELETE
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:619:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_audiomute;
                    ^~~~~~~~~~~~~~~~
streamdeck:623:9: error: 'consumerKeyPressed' was not declared in this scope
         consumerKeyPressed=MEDIA_PLAY_PAUSE;
         ^~~~~~~~~~~~~~~~~~
streamdeck:623:28: error: 'MEDIA_PLAY_PAUSE' was not declared in this scope
         consumerKeyPressed=MEDIA_PLAY_PAUSE;
                            ^~~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:624:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_playpause;
                    ^~~~~~~~~~~~~~~~
streamdeck:628:28: error: 'MEDIA_PREVIOUS' was not declared in this scope
         consumerKeyPressed=MEDIA_PREVIOUS;
                            ^~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:629:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_back;
                    ^~~~~~~~~~~
streamdeck:633:28: error: 'MEDIA_NEXT' was not declared in this scope
         consumerKeyPressed=MEDIA_NEXT;
                            ^~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:634:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_forward;
                    ^~~~~~~~~~~~~~
streamdeck:638:20: error: 'KEY_VOLUME_DOWN' was not declared in this scope
         keyPressed=KEY_VOLUME_DOWN;
                    ^~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:638:20: note: suggested alternative: 'KEY_PAGE_DOWN'
         keyPressed=KEY_VOLUME_DOWN;
                    ^~~~~~~~~~~~~~~
                    KEY_PAGE_DOWN
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:639:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_audiovolumedown;
                    ^~~~~~~~~~~~~~~~~~~~~~
streamdeck:643:20: error: 'KEY_VOLUME_UP' was not declared in this scope
         keyPressed=KEY_VOLUME_UP;
                    ^~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:643:20: note: suggested alternative: 'KEY_PAGE_UP'
         keyPressed=KEY_VOLUME_UP;
                    ^~~~~~~~~~~~~
                    KEY_PAGE_UP
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:644:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_audiovolumeup;
                    ^~~~~~~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:649:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_screenshot;
                    ^~~~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:654:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_screenshot;
                    ^~~~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:659:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_spectacle;
                    ^~~~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:664:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_layout;
                    ^~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:669:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_boot;
                    ^~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:674:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_boot;
                    ^~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:679:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_konsole;
                    ^~~~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:684:20: warning: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
         bitmapName=bitmap_lock;
                    ^~~~~~~~~~~
streamdeck:689:6: error: 'keyPressed' was not declared in this scope
   if(keyPressed!=KEY_RESERVED || consumerKeyPressed!=0) {
      ^~~~~~~~~~
streamdeck:689:18: error: 'KEY_RESERVED' was not declared in this scope
   if(keyPressed!=KEY_RESERVED || consumerKeyPressed!=0) {
                  ^~~~~~~~~~~~
C:\Users\Brad Woods\Downloads\streamdeck\streamdeck.ino:689:18: note: suggested alternative: 'KEY_RETURN'
   if(keyPressed!=KEY_RESERVED || consumerKeyPressed!=0) {
                  ^~~~~~~~~~~~
                  KEY_RETURN
streamdeck:689:34: error: 'consumerKeyPressed' was not declared in this scope
   if(keyPressed!=KEY_RESERVED || consumerKeyPressed!=0) {
                                  ^~~~~~~~~~~~~~~~~~
exit status 1
'KeyboardKeycode' does not name a type; did you mean 'Keyboard'?

**Comment by Bradw-17** [comment]
Figured it out, was missing the HID-Project library

**Comment by fabriziofiorucci** [comment]
Thank you for updating the issue!
